/* @flow */

// GET CUSTOMERS
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';

// DELETE CUSTOMER
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';

// GET CUSTOMER_INVOICES
export const GET_CUSTOMER_INVOICES_SUCCESS = 'GET_CUSTOMER_INVOICES_SUCCESS';
export const GET_CUSTOMER_INVOICES_ERROR = 'GET_CUSTOMER_INVOICES_ERROR';
